# config.yaml

short_description_threshold: 20
min_job_descriptions: 2
max_job_descriptions: 100
default_category_name: "Other"
min_desc_length: 50
min_jobs: 2

# --- Stop Words ---
# A comprehensive list of common words to be excluded from keyword analysis.
# This list is very extensive to filter out noise from job descriptions.
stop_words:
  - a
  - about
  - above
  - across
  - adept
  - after
  - again
  - against
  - able
  - all
  - am
  - an
  - and
  - any
  - apply
  - are
  - area
  - aren't
  - as
  - aspect
  - assist
  - associate
  - at
  - ability
  - approach
  - accurate
  - accurately
  - accountable
  - action
  - adept
  - administer
  - agile
  - allows
  - along
  - already
  - always
  - amongst
  - analyst
  - another
  - anyway
  - anywhere
  - apart
  - appropriate
  - approximately
  - architecture
  - around
  - assess
  - associated
  - assuring
  - ate
  - available
  - average
  - background
  - based
  - be
  - because
  - been
  - before
  - being
  - below
  - benefits
  - best
  - better
  - between
  - bi
  - both
  - but
  - by
  - can
  - candidate
  - certain
  - challenge
  - change
  - client
  - closely
  - collaboration
  - comfortable
  - company
  - component
  - compliance
  - comprehensive
  - condition
  - contribute
  - could
  - currently
  - customer
  - day
  - detail
  - detailed
  - description
  - design
  - development
  - different
  - directly
  - discussion
  - document
  - domain
  - do
  - does
  - doing
  - down
  - duty
  - during
  - each
  - eager
  - effectively
  - efficiently
  - element
  - ensure
  - essential
  - excited
  - excellent
  - excited
  - expert
  - experience
  - factor
  - familiar
  - few
  - field
  - first
  - for
  - from
  - frontend
  - future
  - further
  - general
  - generally
  - given
  - global
  - goal
  - good
  - great
  - greetings
  - growth
  - guideline
  - had
  - has
  - have
  - having
  - he
  - hello
  - help
  - her
  - here
  - hers
  - herself
  - hi
  - highly
  - him
  - himself
  - hire
  - his
  - how
  - i
  - if
  - improvement
  - including
  - indirectly
  - industry
  - information
  - innovation
  - input
  - inside
  - interaction
  - internal
  - international
  - into
  - is
  - issue
  - it
  - its
  - itself
  - job
  - join
  - junior
  - just
  - key
  - knowledge
  - last
  - lead
  - learning
  - level
  - local
  - looking
  - main
  - manage
  - manager
  - many
  - market
  - master
  - me
  - meeting
  - methodology
  - month
  - more
  - most
  - much
  - multiple
  - must
  - my
  - myself
  - national
  - need
  - new
  - next
  - no
  - normally
  - nor
  - not
  - now
  - objective
  - offer
  - of
  - off
  - often
  - on
  - ongoing
  - once
  - only
  - ongoing
  - opportunity
  - or
  - organization
  - other
  - outcome
  - our
  - ours
  - ourselves
  - out
  - output
  - over
  - overview
  - own
  - participate
  - particular
  - partner
  - part
  - past
  - passion
  - perform
  - per
  - platform
  - please
  - policy
  - position
  - practice
  - present
  - presentation
  - previous
  - primary
  - problem
  - procedure
  - process
  - proficient
  - program
  - project
  - protocol
  - provided
  - proven
  - purpose
  - qualifications
  - quickly
  - r
  - ready
  - re
  - regard
  - regarding
  - regards
  - regularly
  - regulation
  - related
  - report
  - requirement
  - required
  - respect
  - responsibilities
  - responsible
  - result
  - right
  - role
  - s
  - same
  - second
  - section
  - sector
  - seeking
  - senior
  - several
  - she
  - should
  - skills
  - so
  - solution
  - some
  - sometimes
  - specific
  - stakeholder
  - standard
  - strong
  - structure
  - such
  - summary
  - support
  - system
  - t
  - task
  - team
  - technology
  - term
  - thanks
  - than
  - that
  - the
  - their
  - theirs
  - them
  - themselves
  - then
  - there
  - these
  - they
  - third
  - this
  - those
  - thorough
  - through
  - to
  - too
  - tool
  - total
  - training
  - transformation
  - typically
  - understanding
  - under
  - until
  - upcoming
  - up
  - usually
  - using
  - various
  - vendor
  - very
  - want
  - was
  - we
  - week
  - well
  - were
  - what
  - when
  - where
  - which
  - while
  - who
  - whole
  - whom
  - why
  - will
  - with
  - within
  - whole
  - will
  - with
  - work
  - working
  - within
  - you
  - year
  - your
  - yours
  - yourself
  - yourselves

# --- Additional Stop Words ---
# Add any custom stop words here that are specific to your domain.
# Words listed here will be *added* to the base stop_words list above.
stop_words_add: []

# --- Stop Words to Exclude ---
# If you want to *keep* a word that's normally considered a stop word, list it here.
# Words listed here will be *removed* from the base stop_words list above.
stop_words_exclude: []

# --- Skills Whitelist ---
# A highly comprehensive list of skills and technologies relevant to various tech and product roles.
# This list is crucial for accurate keyword extraction. Expand and customize it as needed.
skills_whitelist:
  - python
  - sql
  - java
  - javascript
  - typescript
  - react
  - angular
  - vue
  - node.js
  - node
  - aws
  - azure
  - gcp
  - google cloud platform
  - amazon web services
  - microsoft azure
  - docker
  - kubernetes
  - excel
  - powerpoint
  - tableau
  - power bi
  - tensorflow
  - pytorch
  - keras
  - scikit-learn
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - git
  - github
  - gitlab
  - bitbucket
  - jira
  - confluence
  - slack
  - agile
  - scrum
  - kanban
  - devops
  - ci/cd
  - continuous integration
  - continuous delivery
  - continuous deployment
  - ml
  - ai
  - machine learning
  - artificial intelligence
  - nlp
  - natural language processing
  - api
  - rest
  - restful api
  - graphql
  - mongodb
  - postgresql
  - mysql
  - redis
  - elasticsearch
  - data analysis
  - data analytics
  - data visualization
  - data warehousing
  - data mining
  - database management
  - product management
  - product development
  - deep learning
  - communication
  - negotiation
  - problem-solving
  - time management
  - leadership
  - teamwork
  - critical thinking
  - adaptability
  - project management
  - business analysis
  - strategy
  - strategic planning
  - product strategy
  - roadmapping
  - product roadmap
  - market research
  - competitive analysis
  - user research
  - customer research
  - user stories
  - backlog management
  - prioritization
  - go-to-market
  - go-to-market strategy
  - product lifecycle
  - product lifecycle management
  - plm
  - saas
  - software as a service
  - ux
  - user experience
  - ui
  - user interface
  - wireframing
  - prototyping
  - a/b testing
  - mvp
  - minimum viable product
  - product analytics
  - web analytics
  - google analytics
  - adobe analytics
  - stakeholder management
  - presentation skills
  - requirements elicitation
  - requirements analysis
  - requirements gathering
  - requirements management
  - process modeling
  - process improvement
  - business process modeling
  - uml
  - unified modeling language
  - bpmn
  - business process model and notation
  - use cases
  - user acceptance testing
  - uat
  - testing
  - software testing
  - quality assurance
  - qa
  - data modeling
  - business process reengineering
  - bpr
  - documentation
  - technical writing
  - risk management
  - budget management
  - resource management
  - scope management
  - project planning
  - project execution
  - project monitoring
  - project control
  - waterfall
  - prince2
  - pmp
  - project management professional
  - gantt charts
  - gantt chart
  - critical path
  - critical path method
  - cpm
  - communication planning
  - change management
  - issue tracking
  - issue resolution
  - conflict resolution
  - agile methodologies
  - scrum master
  - certified scrum master
  - csm
  - product owner
  - certified product owner
  - cspo
  - sprint planning
  - sprint review
  - sprint retrospective
  - daily scrum
  - daily standup
  - iterative development
  - incremental development
  - sprint
  - sprint backlog
  - backlog grooming
  - definition of done
  - planning poker
  - retrospective
  - scope creep
  - standup
  - story point
  - lean software development
  - lsd
  - customer journey mapping
  - empathy mapping
  - design thinking
  - lean startup
  - user persona
  - product marketing manager
  - product operations
  - acceptance criteria
  - feature factory
  - feature-less roadmap
  - general availability
  - ga
  - implicit requirements
  - intuitive design
  - mockup
  - pivot
  - sunk cost
  - swot analysis
  - technical debt
  - turnover rate
  - unique selling proposition
  - usp
  - usability testing
  - use case
  - value proposition
  - vanity metrics
  - weighted scoring
  - wireframe
  - program manager
  - technical product manager
  - alpha test
  - beta test
  - digital transformation
  - end-user era

# --- Allowed Entity Types for NER ---
# Specify which named entity types to extract using spaCy's Named Entity Recognition (NER).
# Common and useful types for job description analysis are listed below.
# - ORG: Organizations (companies, agencies, etc.)
# - PRODUCT: Product names
# - GPE: Geopolitical entities (countries, cities, states)
# - EVENT: Named events (conferences, wars, etc.)
# - WORK_OF_ART: Titles of books, songs, etc.
# - LAW: Named laws and legal documents
# - PERSON: People's names (generally less useful for job skills)
# - DATE: Dates and times (generally less useful for job skills)
# - MONEY: Monetary values (generally less useful for job skills)
allowed_entity_types:
  - ORG
  - PRODUCT
  - GPE
  - EVENT
  - WORK_OF_ART
  - LAW

# --- Output Directory ---
# Directory where the output Excel file will be saved.
output_dir: output

# --- Keyword Categories ---
# Define categories to group extracted keywords for better organization in the output.
# Keywords listed under each category are used for *substring matching*.
# For example, if "machine learning engineer" is extracted and "machine learning" is under "Technical Skills",
# then "machine learning engineer" will be categorized as "Technical Skills".
keyword_categories:
  Technical Skills:
    - python
    - sql
    - java
    - javascript
    - typescript
    - react
    - angular
    - vue
    - node
    - aws
    - azure
    - gcp
    - docker
    - kubernetes
    - excel
    - powerpoint
    - tableau
    - power bi
    - tensorflow
    - pytorch
    - keras
    - scikit-learn
    - pandas
    - numpy
    - matplotlib
    - seaborn
    - git
    - jira
    - confluence
    - slack
    - mongodb
    - postgresql
    - mysql
    - redis
    - elasticsearch
    - data analysis
    - ml
    - ai
    - machine learning
    - deep learning
    - natural language processing
    - nlp
    - api
    - rest
    - graphql
    - ci/cd
    - data visualization
    - big data
    - cloud computing
    - html
    - css
    - mobile development
    - frontend development
    - backend development
    - full stack development
    - statistical modeling
    - data mining
    - computer vision
    - time series analysis
    - regression analysis
    - classification
    - clustering
    - dimensionality reduction
    - feature engineering
    - model selection
    - hyperparameter tuning
    - a/b testing
    - etl
    - devops
    - continuous integration
    - continuous delivery
    - continuous deployment
    - version control
    - testing
    - unit testing
    - integration testing
    - system testing
    - user acceptance testing
    - uat
    - performance testing
    - load testing
    - stress testing
    - security testing
    - penetration testing
    - vulnerability assessment
    - cross-platform development
    - flutter
    - react native
    - xamarin
    - swift
    - objective-c
    - kotlin
    - api design
    - microservices
    - serverless
    - cloud functions
    - lambda
    - azure functions
    - google cloud functions
    - containerization
    - orchestration
    - linux
    - unix
    - windows server
    - shell scripting
    - bash
    - powershell
    - networking
    - tcp/ip
    - http
    - https
    - dns
    - load balancing
    - firewalls
    - vpn
    - cybersecurity
    - information security
    - threat modeling
    - risk assessment
    - incident response
    - business intelligence
    - bi
    - reporting
    - dashboards
    - data storytelling
    - statistical analysis # Added statistical analysis to technical skills

  Soft Skills:
    - communication
    - negotiation
    - problem-solving
    - time management
    - leadership
    - teamwork
    - critical thinking
    - adaptability
    - presentation skills
    - collaboration
    - organizational skills
    - analytical skills
    - client management
    - customer service
    - interpersonal skills # Added interpersonal skills as a soft skill

  Industry Knowledge:
    - project management
    - business analysis
    - product management
    - devops
    - agile
    - scrum
    - kanban
    - jira
    - confluence
    - saas
    - software as a service
    - product lifecycle management
    - plm
    - data governance
    - data quality
    - data security
    - data privacy
    - gdpr
    - ccpa
    - market research
    - competitive analysis
    - user research
    - customer research
    - strategic planning
    - product strategy
    - roadmapping
    - product roadmap
    - requirements elicitation
    - requirements analysis
    - requirements gathering
    - requirements management
    - process modeling
    - process improvement
    - business process modeling
    - uml
    - bpmn
    - business process model and notation
    - use cases
    - user acceptance testing
    - uat
    - quality assurance
    - qa
    - data modeling
    - business process reengineering
    - bpr
    - risk management
    - budget management
    - resource management
    - scope management
    - project planning
    - project execution
    - project monitoring
    - project control
    - waterfall
    - prince2
    - pmp
    - project management professional
    - gantt charts
    - gantt chart
    - critical path
    - critical path method
    - cpm
    - communication planning
    - change management
    - issue tracking
    - issue resolution
    - conflict resolution
    - agile methodologies
    - scrum master
    - certified scrum master
    - csm
    - product owner
    - certified product owner
    - cspo
    - sprint planning
    - sprint review
    - sprint retrospective
    - daily scrum
    - daily standup
    - iterative development
    - incremental development
    - sprint
    - sprint backlog
    - backlog grooming
    - definition of done
    - planning poker
    - retrospective
    - scope creep
    - standup
    - story point
    - lean software development
    - lsd
    - customer journey mapping
    - empathy mapping
    - design thinking
    - lean startup
    - user persona
    - product marketing manager
    - product operations
    - go-to-market strategy
    - product lifecycle
    - requirements management

  Other: []  # Keywords that don't neatly fit into the above categories. Customize as needed.

ngram_range: [1, 3]
similarity_threshold: 0.7

weighting:
  tfidf_weight: 0.7
  frequency_weight: 0.3
  whitelist_boost: 1.5